version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
        - ./jitsi_targets.yml:/etc/prometheus/jitsi_targets.yml
        - ./mm_targets.yml:/etc/prometheus/mm_targets.yml
        - prometheus_data:/prometheus
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    ports:
        - '127.0.0.1:9090:9090'
  blackbox_exporter:
    image: prom/blackbox-exporter
    ports:
        - '127.0.0.1:9115:9115'
    dns: 1.1.1.1
    restart: unless-stopped
    volumes:
      - "./blackbox.yml:/blackbox.yml"
    command: --config.file=/blackbox.yml
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_SERVER_ROOT_URL
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
  www_table:
    image: python:3.7-slim-buster
    command: "python3 /scrape_prometheus.py"
    stop_signal: SIGKILL
    volumes:
      - ./hosts.json:/hosts.json
      - "./scrape_prometheus.py:/scrape_prometheus.py"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  prometheus_data: {}
  grafana_data: {}
