---
global:
  external_labels:
    monitor: "iorestoacasa.work monitoring"
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - "localhost:9090"
  - job_name: monitor
    file_sd_configs:
      - files:
        - "jitsi_targets.yml"
        refresh_interval: 10s
  - job_name: blackbox 
    metrics_path: /metrics
    static_configs:
      - targets:
        - blackbox_exporter:9115
  - job_name: blackbox-http
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
    file_sd_configs:
      - files:
        - "mm_targets.yml"
        refresh_interval: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115